# Generated by Django 3.1.7 on 2021-03-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=150)),
                ('mother_mark', models.CharField(max_length=150)),
                ('mother_type', models.CharField(max_length=150)),
                ('mother_made', models.CharField(max_length=150)),
                ('mother_doc', models.CharField(max_length=150)),
                ('mother_status', models.CharField(max_length=150)),
                ('red_type', models.CharField(max_length=150)),
                ('red_mark', models.CharField(max_length=150)),
                ('red_designation', models.CharField(max_length=150)),
                ('red_nominal', models.CharField(max_length=150)),
                ('red_efficiency', models.CharField(max_length=150)),
                ('red_made', models.CharField(max_length=150)),
                ('red_doc', models.CharField(max_length=150)),
                ('red_status', models.CharField(max_length=150)),
                ('orange_type', models.CharField(max_length=150)),
                ('orange_mark', models.CharField(max_length=150)),
                ('orange_designation', models.CharField(max_length=150)),
                ('orange_nominal', models.CharField(max_length=150)),
                ('orange_efficiency', models.CharField(max_length=150)),
                ('orange_made', models.CharField(max_length=150)),
                ('orange_doc', models.CharField(max_length=150)),
                ('orange_status', models.CharField(max_length=150)),
                ('yellow_type', models.CharField(max_length=150)),
                ('yellow_mark', models.CharField(max_length=150)),
                ('yellow_designation', models.CharField(max_length=150)),
                ('yellow_nominal', models.CharField(max_length=150)),
                ('yellow_efficiency', models.CharField(max_length=150)),
                ('yellow_made', models.CharField(max_length=150)),
                ('yellow_doc', models.CharField(max_length=150)),
                ('yellow_status', models.CharField(max_length=150)),
                ('green_type', models.CharField(max_length=150)),
                ('green_mark', models.CharField(max_length=150)),
                ('green_designation', models.CharField(max_length=150)),
                ('green_nominal', models.CharField(max_length=150)),
                ('green_efficiency', models.CharField(max_length=150)),
                ('green_made', models.CharField(max_length=150)),
                ('green_doc', models.CharField(max_length=150)),
                ('green_status', models.CharField(max_length=150)),
                ('blue_type', models.CharField(max_length=150)),
                ('blue_mark', models.CharField(max_length=150)),
                ('blue_designation', models.CharField(max_length=150)),
                ('blue_nominal', models.CharField(max_length=150)),
                ('blue_efficiency', models.CharField(max_length=150)),
                ('blue_made', models.CharField(max_length=150)),
                ('blue_doc', models.CharField(max_length=150)),
                ('blue_status', models.CharField(max_length=150)),
                ('indigo_type', models.CharField(max_length=150)),
                ('indigo_mark', models.CharField(max_length=150)),
                ('indigo_designation', models.CharField(max_length=150)),
                ('indigo_nominal', models.CharField(max_length=150)),
                ('indigo_efficiency', models.CharField(max_length=150)),
                ('indigo_made', models.CharField(max_length=150)),
                ('indigo_doc', models.CharField(max_length=150)),
                ('indigo_status', models.CharField(max_length=150)),
                ('violet_type', models.CharField(max_length=150)),
                ('violet_mark', models.CharField(max_length=150)),
                ('violet_designation', models.CharField(max_length=150)),
                ('violet_nominal', models.CharField(max_length=150)),
                ('violet_efficiency', models.CharField(max_length=150)),
                ('violet_made', models.CharField(max_length=150)),
                ('violet_doc', models.CharField(max_length=150)),
                ('violet_status', models.CharField(max_length=150)),
                ('coord', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
